package com.example.data

import kotlin.math.ceil
import kotlin.math.max

/** One level of a progressively downsampled terrain pyramid. */
data class TerrainLodLevel(
    val reductionFactor: Int,
    val grid: ElevationGrid,
)

/**
 * Memory-bounded terrain levels used by the GPU renderer and zoom-aware preview work.
 *
 * The source grid is never modified. Levels are generated by 2×2 aggregation and preserve
 * no-data coverage, average bare-earth elevation, and maximum canopy height per output cell.
 */
class TerrainLodPyramid private constructor(
    val levels: List<TerrainLodLevel>,
) {
    init {
        require(levels.isNotEmpty())
    }

    /** Finest level first. */
    val finest: TerrainLodLevel get() = levels.first()
    val coarsest: TerrainLodLevel get() = levels.last()

    fun selectForZoom(zoom: Float): TerrainLodLevel {
        if (levels.size == 1) return levels.first()
        val safeZoom = zoom.coerceAtLeast(1f)
        val desiredFactor = when {
            safeZoom >= 8f -> 1
            safeZoom >= 4f -> 2
            safeZoom >= 2f -> 4
            else -> Int.MAX_VALUE
        }
        return if (desiredFactor == Int.MAX_VALUE) {
            coarsest
        } else {
            levels.minByOrNull { kotlin.math.abs(it.reductionFactor - desiredFactor) } ?: finest
        }
    }

    fun estimatedBytes(): Long = levels.sumOf { level ->
        val cells = level.grid.width.toLong() * level.grid.height.toLong()
        cells * 9L
    }

    companion object {
        /**
         * Creates a pyramid whose finest level is capped to [maxFinestDimension]. This keeps GPU
         * vertex/index buffers bounded even when the CPU analysis raster is 1024².
         */
        fun build(
            source: ElevationGrid,
            maxFinestDimension: Int = 512,
            minDimension: Int = 64,
            maxLevels: Int = 4,
        ): TerrainLodPyramid {
            require(maxFinestDimension >= 64)
            require(minDimension >= 16)
            require(maxLevels >= 1)

            var reduction = 1
            var current = source
            while (max(current.width, current.height) > maxFinestDimension) {
                current = downsample2x(current)
                reduction *= 2
            }

            val levels = ArrayList<TerrainLodLevel>(maxLevels)
            levels += TerrainLodLevel(reduction, current)
            while (
                levels.size < maxLevels &&
                max(current.width, current.height) > minDimension &&
                current.width > 2 && current.height > 2
            ) {
                current = downsample2x(current)
                reduction *= 2
                levels += TerrainLodLevel(reduction, current)
            }
            return TerrainLodPyramid(levels)
        }

        internal fun downsample2x(source: ElevationGrid): ElevationGrid {
            val width = ceil(source.width / 2.0).toInt().coerceAtLeast(1)
            val height = ceil(source.height / 2.0).toInt().coerceAtLeast(1)
            val bare = FloatArray(width * height)
            val canopy = FloatArray(width * height)
            val valid = BooleanArray(width * height)

            for (y in 0 until height) {
                for (x in 0 until width) {
                    var elevationSum = 0.0
                    var elevationCount = 0
                    var maxCanopy = 0f
                    for (dy in 0..1) {
                        for (dx in 0..1) {
                            val sx = x * 2 + dx
                            val sy = y * 2 + dy
                            if (sx !in 0 until source.width || sy !in 0 until source.height) continue
                            val sourceIndex = sy * source.width + sx
                            if (!source.validData[sourceIndex]) continue
                            elevationSum += source.bareEarth[sourceIndex]
                            elevationCount++
                            maxCanopy = max(maxCanopy, source.canopySpikes[sourceIndex])
                        }
                    }
                    val outputIndex = y * width + x
                    if (elevationCount > 0) {
                        valid[outputIndex] = true
                        bare[outputIndex] = (elevationSum / elevationCount).toFloat()
                        canopy[outputIndex] = maxCanopy
                    }
                }
            }

            return ElevationGrid(
                width = width,
                height = height,
                bareEarth = bare,
                canopySpikes = canopy,
                cellSizeMeters = source.cellSizeMeters * 2f,
                validData = valid,
            )
        }
    }
}

/** Coarse spatial index used to skip empty flight-line gaps and create bounded GPU batches. */
data class TerrainSpatialTile(
    val tileColumn: Int,
    val tileRow: Int,
    val startX: Int,
    val startY: Int,
    val endXInclusive: Int,
    val endYInclusive: Int,
    val validCellCount: Int,
    val minElevation: Float,
    val maxElevation: Float,
) {
    val isEmpty: Boolean get() = validCellCount == 0
}

class TerrainSpatialGridIndex private constructor(
    val gridWidth: Int,
    val gridHeight: Int,
    val tileSize: Int,
    val columns: Int,
    val rows: Int,
    val tiles: List<TerrainSpatialTile>,
) {
    fun nonEmptyTiles(): List<TerrainSpatialTile> = tiles.filterNot(TerrainSpatialTile::isEmpty)

    fun query(bounds: NormalizedRasterBounds): List<TerrainSpatialTile> {
        val safe = bounds.sanitized()
        val minX = (safe.left * gridWidth).toInt().coerceIn(0, gridWidth - 1)
        val maxX = (safe.right * gridWidth).toInt().coerceIn(minX, gridWidth - 1)
        val minY = (safe.top * gridHeight).toInt().coerceIn(0, gridHeight - 1)
        val maxY = (safe.bottom * gridHeight).toInt().coerceIn(minY, gridHeight - 1)
        return tiles.filter { tile ->
            !tile.isEmpty &&
                tile.endXInclusive >= minX && tile.startX <= maxX &&
                tile.endYInclusive >= minY && tile.startY <= maxY
        }
    }

    companion object {
        fun build(grid: ElevationGrid, tileSize: Int = 64): TerrainSpatialGridIndex {
            require(tileSize in 16..256)
            val columns = ceil(grid.width / tileSize.toDouble()).toInt()
            val rows = ceil(grid.height / tileSize.toDouble()).toInt()
            val tiles = ArrayList<TerrainSpatialTile>(columns * rows)

            for (tileRow in 0 until rows) {
                for (tileColumn in 0 until columns) {
                    val startX = tileColumn * tileSize
                    val startY = tileRow * tileSize
                    val endX = (startX + tileSize).coerceAtMost(grid.width - 1)
                    val endY = (startY + tileSize).coerceAtMost(grid.height - 1)
                    var count = 0
                    var minElevation = Float.MAX_VALUE
                    var maxElevation = -Float.MAX_VALUE
                    for (y in startY..endY) {
                        for (x in startX..endX) {
                            val index = y * grid.width + x
                            if (!grid.validData[index]) continue
                            val elevation = grid.bareEarth[index]
                            if (!elevation.isFinite()) continue
                            count++
                            if (elevation < minElevation) minElevation = elevation
                            if (elevation > maxElevation) maxElevation = elevation
                        }
                    }
                    tiles += TerrainSpatialTile(
                        tileColumn = tileColumn,
                        tileRow = tileRow,
                        startX = startX,
                        startY = startY,
                        endXInclusive = endX,
                        endYInclusive = endY,
                        validCellCount = count,
                        minElevation = if (count > 0) minElevation else 0f,
                        maxElevation = if (count > 0) maxElevation else 0f,
                    )
                }
            }

            return TerrainSpatialGridIndex(
                gridWidth = grid.width,
                gridHeight = grid.height,
                tileSize = tileSize,
                columns = columns,
                rows = rows,
                tiles = tiles,
            )
        }
    }
}
